#!/usr/bin/env bash

# Add the brew bin folder to the PATH variable.
export PATH="/usr/local/sbin:$PATH"

# Ask for the administrator password upfront.
sudo -v

# Keep-alive: update existing `sudo` time stamp until the script has finished.
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Install command-line tools.
xcode-select --install

# Install dotfiles
./scripts/dotfiles --force

# Remove outdated versions from the cellar and update brew.
brew cleanup && brew update

./scripts/brew-install
./scripts/brew-install-php
./scripts/install-node

# Remove outdated casks from the cellar and update cask.
brew cask cleanup && brew cask update

# Upgrade all existing casks
./scripts/brew-cask-update
./scripts/brew-cask-install

# Remove outdated versions from the cellars.
brew cleanup && brew cask cleanup

if [ -f "$HOME/.zshrc" ]; then
    source "$HOME/.zshrc";
fi
