#!/usr/bin/env bash

brew install php@7.1

echo 'export PATH="/usr/local/opt/php@7.1/bin:$PATH"' >> ~/.php@7.1
echo 'export PATH="/usr/local/opt/php@7.1/sbin:$PATH"' >> ~/.php@7.1

brew link php@7.1

pecl install imagick
pecl install intl
pecl install xdebug
pecl install mongodb