#!/usr/bin/env bash

# Install missing casks
brew cask install 1password
brew cask install alfred appcleaner avg-antivirus
brew cask install caffeine ccleaner
brew cask install dash datagrip
brew cask install google-chrome google-drive
brew cask install iterm2
brew cask install java
brew cask install libreoffice
brew cask install paw phpstorm
brew cask install sequel-pro slack sourcetree spectacle studio-3t sublime-text
brew cask install tunnelblick
brew cask install vagrant virtualbox vnc-viewer
brew cask install whatsapp
